### ISSUE TITLE
Error in the docs

### ISSUE THREAD

**Issue by alexfurr** [phpfui/icalendar#2]
Thanks again for sorting this useful library out and making it live again.

Some errors in the docs that caused me a headache and some code searching.

All instances of:
```\ICalendarOrg\ZCiCal::fromSqlDateTime();```
should be:
```\ICalendarOrg\ZDateHelper::fromSqlDateTime();```
Cheers,
Alex

**Comment by phpfui** [comment]
Thanks for the feedback!  It should now be fixed.  I incremented the version so my PHPFUI documentation site will be updated tonight.

Glad you found the new version!
