### ISSUE TITLE
Mistake in splitting of long content lines

### ISSUE THREAD

**Issue by alexanderaltendorfer** [phpfui/icalendar#6]
Hello,

there seems to be a small issue in ZCiCalDataNode.php:138 that prevents events with long content lines from importing into Apple Calendar.

Instead of
`$part = $part . \substr($value, 0, 67) . " \r\n";`
it should read
`$part = $part . \substr($value, 0, 67) . "\r\n ";`

See [https://icalendar.org/iCalendar-RFC-5545/3-1-content-lines.html](https://icalendar.org/iCalendar-RFC-5545/3-1-content-lines.html)
"That is, a long line can be split between any two characters by inserting a CRLF immediately followed by a single linear white-space character (i.e., SPACE or HTAB)."

**Comment by phpfui** [comment]
Thanks for the heads up.

I am not sure I can test Apple Calendar, as I use Windows and Android.  Can you set your composer dependency to dev-master and test locally. Once you think it works, let me know and I can stamp a new version.

**Comment by alexanderaltendorfer** [comment]
Thank you for the quick update. I pulled the dev-master branch and saw your changes. There is still one white-space missing after the CRLF. The space is mandatory according to the iCalendar specs, to be able to parse these split lines. So it should look like this: `"\r\n "` with a space right after the `\n`

**Comment by phpfui** [comment]
Try it now.

**Comment by alexanderaltendorfer** [comment]
Perfect, this is now working for me in Apple Calendar. If it is also (still) working in your tests on Windows and Android we are good to go. Thanks!

**Comment by phpfui** [comment]
Now released.  Thanks for the heads up!
